### ISSUE TITLE
Make equipment list a table with fixed tabs so you get columns with name and trashcan lined in vertical order (add encumbrance column).

### ISSUE THREAD

**Issue by ForjaSalvaje** [Foundry-VTT-Lex-Arcana/foundryvtt-lexarcana#37]

**Comment by parvusdomus** [comment]
This one is next when I go over the inventory overhaul polishing

**Comment by parvusdomus** [comment]
Still using an unordered list instead of a table (I prefer it this way) but fixed the columns size for it to look properly.
Please close
