### ISSUE TITLE
Disable roll buttons when 2 or 3 dice are not possible.

### ISSUE THREAD

**Issue by ForjaSalvaje** [Foundry-VTT-Lex-Arcana/foundryvtt-lexarcana#51]
Detect when 2 or 3 dice, because of small values, are not possible and grey out those buttons. For example if you have value 3,4,5 point values then only 1 die is possible to roll. Same with values 6,7,8 points only 1 or 2 dice are allowed. Value 9 is 3d3 and it is the first value where you can use 3 dice on Roll.

**Comment by pplans** [comment]
Done
