### ISSUE TITLE
Control Peritiae Specialization value input

### ISSUE THREAD

**Issue by ForjaSalvaje** [Foundry-VTT-Lex-Arcana/foundryvtt-lexarcana#53]
You can set value to +1 instead of 1 and it shows NULL on Roll dialog. Maybe clean value to be integer only? If set to 0 delete or remove?

**Comment by parvusdomus** [comment]
works for me with +1 or just 1 in specialization.

**Comment by ForjaSalvaje** [comment]
Maybe it was fixed. Closing.
