### ISSUE TITLE
Idigamentum object description text is not displayed after saving but it is there

### ISSUE THREAD

**Issue by ForjaSalvaje** [Foundry-VTT-Lex-Arcana/foundryvtt-lexarcana#65]

**Comment by parvusdomus** [comment]
Fixed, please close

**Comment by ForjaSalvaje** [comment]
Is it included in the PR?

**Comment by parvusdomus** [comment]
Yep, should be in my previous one (this one was fixed when I fixed all the item sheets that where pointing to wrong data paths and creating duplicated values)

------- Original Message -------

**Comment by ForjaSalvaje** [comment]
Yes, it is fixed. Thank you!
