### ISSUE TITLE
Add are you sure to delete Specialization (it does delete it without asking confirmation)

### ISSUE THREAD

**Issue by ForjaSalvaje** [Foundry-VTT-Lex-Arcana/foundryvtt-lexarcana#69]

**Comment by parvusdomus** [comment]
I'll take this one, shouldn't be hard to add a confirmation dialog, I'll have to add one as part of the rituals tab overhaul, so probably is just using the same code anyway

**Comment by parvusdomus** [comment]
Done for v10, when you update to v10 and confirm it is fixed, please close
