### ISSUE TITLE
Add a way to edit/view/remove the province in the custos sheet

### ISSUE THREAD

**Issue by parvusdomus** [Foundry-VTT-Lex-Arcana/foundryvtt-lexarcana#92]
Even though the province can be swapped by drag-and-drop and that should be enough to play I think I'd like better to have a couple small buttons to edit/remove the province in the custos sheet.

This one is not a priority at all and I could take care of it myself when I have some time.

**Comment by pplans** [comment]
I will need more details on that if you can provide am not sure I agree so if you could precise a bit more in terms of impact, data

**Comment by parvusdomus** [comment]
Nah, forget it, silly idea. I tought again about it and I think this is not needed at all. Better to leave it as is.
